### ISSUE TITLE
Logarithmic scale for axis

### ISSUE THREAD

**Issue by 0x7CFE** [38/plotters#1]
First of all, I would like to say thank you for such an amazing library! I really like your approach. Hope it will evolve to be a de-facto standard for Rust graphics.

The question is: how am I supposed to configure plotter to draw in an logarithmic scale? I am particularly interested in a logarithmic histograms.

**Comment by 38** [comment]
I'm glad you finding its useful. Previously the logarithmic coordinate is planned but not yet support.

Now I make the change, so that it can support log coordinate. Now you can pass `LogRange` wrapped range to specify the axis is log scale ! 

```
 let mut chart = ChartBuilder::on(&root)
        .x_label_area_size(25)
        .y_label_area_size(40)
        .caption("Histogram Test", &font)
        .build_ranged(0u32..10u32, LogRange(0u32..10u32));
```

Also, please note the library is in very early stage and I believe I am currently the only user.
But I am more than happy to get more and more people involved !

Hope this is helpful.

**Comment by 0x7CFE** [comment]
> Now you can pass LogRange wrapped range to specify the axis is log scale !

Awesome, thaks! I will give it a try.

> Also, please note the library is in very early stage and I believe I am currently the only user.

Sure, I understand that. Nevertheless, even for a young library plotter demonstrates an impressive amount of features. Looking forward for more to come!
