### ISSUE TITLE
String on X-axis

### ISSUE THREAD

**Issue by gabemgem** [38/plotters#127]
I am trying to make a histogram of the rgb values in an image using ChartBuilder and Histogram. Is there a way to have "Red", "Green", and "Blue" on the x-axis instead of numbers?

**Comment by 38** [comment]
Hi there, sorry for delayed reply. 

Surely you can do that, one solution is you can customize the formatter.

See hehre: https://docs.rs/plotters/0.2.12/plotters/chart/struct.MeshStyle.html#method.x_label_formatter

So that you can have something like:

`chart.configure_mesh().x_label_formatter(|x| ["Red", "Green", "Blue"][*x].to_string())`
