### ISSUE TITLE
Improve font loading

### ISSUE THREAD

**Issue by chrisduerr** [38/plotters#182]
I have a relatively minimal Linux system with not a ton of fonts installed, which is probably the cause for this problem. However I cannot figure out for the life of me how to make any example of plotters work without modifications.

It seems like by default it just doesn't work at all. I'm not sure what the default font is but that's already quite surprising. In general I feel like it should work on any system with at least some font installed.

Running `fc-match` on any of the patterns I've tried will give me a good chunk of fonts to pick from, but things seem to only work out when specifying an exact font name.

I'm a bit confused by this, since I've looked at some of the font-kit code and it's fairly similar to the font loader I've written (partially) myself. Is this fickle font loading solely due to font-kit, or does plotters actually load specific faces here?

**Comment by caemor** [comment]
How did you solve your problem?
When trying to run the histogram example (or others) I get the following error which you seem to have solved on your end:
```     
Running `target/debug/examples/histogram`
Error: BackendError(FontError(FontLoadError(IllFormed)))
```

**Comment by chrisduerr** [comment]
There seem to be two different places where fonts are used: The axes and the series lables. So what I did to fix that was specifying an exact font I know I have installed on my system (replace "Fira Mono" with your font):

```rust
use plotters::prelude::*;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let root = SVGBackend::new("plotters-doc-data/0.svg", (640, 480)).into_drawing_area();
    root.fill(&WHITE)?;
    let mut chart = ChartBuilder::on(&root)
        .caption("y=x^2", ("Fira Mono", 50).into_font())
        .margin(5)
        .x_label_area_size(30)
        .y_label_area_size(30)
        .build_ranged(-1f32..1f32, -0.1f32..1f32)?;

    chart.configure_mesh().draw()?;

    chart
        .draw_series(LineSeries::new(
            (-50..=50).map(|x| x as f32 / 50.0).map(|x| (x, x * x)),
            &RED,
        ))?
        .label("y = x^2")
        .legend(|(x, y)| PathElement::new(vec![(x, y), (x + 20, y)], &RED));

    chart
        .configure_series_labels()
        .label_font(("Fira Mono", 50))
        .background_style(&WHITE.mix(0.8))
        .border_style(&BLACK)
        .draw()?;

    Ok(())
}
```

I also had to switch to use the SVGBackend, which I wanted to do anyways, but the bitmap one didn't work even after these changes.

**Comment by caemor** [comment]
Thanks, switching to the svg backend as well as replacing the font solved the issue for me as well.

**Comment by 38** [comment]
Thank you for reporting the issue.

I guess the error might be related to `rusttype`. Historically, Plotters fully depends on `rusttype` for both rasterizing and loading purpose, but later font-kit was partially replaced the font loading part, but still rasterizing is still based on rusttype.

Particularly the IllFormed error @caemor got might be related to this issue https://github.com/fschutt/printpdf/issues/28.
> ```
> Running `target/debug/examples/histogram`
> Error: BackendError(FontError(FontLoadError(IllFormed)))
> ```

Also @chrisduerr , could you please share what error / output you got from the example? Since if you also got IllFormed error message, that probably explain why.

font-kit seems much portable than rust-type, which I believe is used in project like Servo. I am planning to get rid of `rusttype` completely, hopefully this will address those issue. 

Thanks for the help!

**Comment by chrisduerr** [comment]
> Also @chrisduerr , could you please share what error / output you got from the example? Since if you also got IllFormed error message, that probably explain why.

That was basically all the output. The backtrace was useless pointing just somewhere in std (call_once iirc).

Based on my experience getting rid of `rusttype` in favor of OS-specific libraries would be strongly advised. While in a very limited rasterization context it might make sense, I cannot recommend it as a general-purpose rasterizer.

**Comment by 38** [comment]
Hi there, just land the code that use solely font-kit, I am not sure if this solves the issue on font loading you guys have.

**Comment by chrisduerr** [comment]
That does fix the issue, awesome!

**Comment by spoutn1k** [comment]
Hey I am having the same issue ! What was the fix ? I do not get what @38 meant by 'land', nor where to find that code.

**Comment by PHPirates** [comment]
I'm also having a font error: `Error: BackendError(FontError(FontLoadError(IllFormed)))`, which looks very much like the above.

I'm pretty sure that the exact same code worked before on my system, but after I reinstalled my OS the code doesn't work anymore. So I would think it's because of some missing font that I had previously installed but not anymore.

Anybody an idea how to find out which font is causing the problem? The error does not give any information at all.
