### ISSUE TITLE
Complete support for DateTime and Duration coordinate

### ISSUE THREAD

**Issue by serzhiio** [38/plotters#36]
Is it possible to build chart with seconds or even milliseconds on X-axis? It would be nice to split it by some nice ranges like 5sec or 1/5min?

**Comment by serzhiio** [comment]
It looks like Datetime require only Date not DateTime?
`pub struct RangedDate<Z: TimeZone>(Date<Z>, Date<Z>);`

**Comment by 38** [comment]
That's something I have no chance to implement yet. But I am going to clean this up very soon. 
Basically, both `DateTime` and `Duration` should be supported.

**Comment by serzhiio** [comment]
In datetime mod there is RangedDateTime struct which is not developed.
Is it really needed to have two Date and DateTime coords structs? Why not implement
`IntoMonthly, IntoYearly, Into Hours, Into Minutes, IntoSeconds` for one DateTime struct?

**Comment by serzhiio** [comment]
And use `chrono::DateTime` instead of `chrono::Date`.

**Comment by 38** [comment]
> And use chrono::DateTime instead of chrono::Date.

That is mostly right. But it will cause problem if the `DateTime` range is smaller than one day. 

But we can add additional logic to the existing date handling code make it also produce, hourly, ...., etc.

> Why not implement IntoMonthly, IntoYearly, Into Hours, Into Minutes, IntoSeconds for one DateTime struct?

And I would like to mention the reason why `IntoMonthly` and `IntoYearly` exists is because month and year aren't equally length. Thus, there's many weird things may happen when we want to have monthly or yearly granularity. And this is what those trait for, the reason for there's no `IntoWeekly` and `IntoDaily` is the same, because they always have the same length, and all those need should be fulfilled by tweaking the number of labels.

It seems some amount of work to do to support all those things. I will think about a concrete plan to support this. And I probably have time to address this in a day or two. 

Please let me know if you have any other concerns.

**Comment by 38** [comment]
@serzhiio Just a quick update, monthly and yearly coordinate should be able to accept `DateTime` now. 

I've just refactored a little bit but still not tested it. And the next step should be add code that identify the granularity for a `DateTime` range. And if we need to use a granularity which is bigger than a day, we can simply reuse the code for `Date`. 

I will let you know when this happen

**Comment by serzhiio** [comment]
This sounds sweet. I'd like to help, but your code a bit complicated for me (too many traits :))
I'm exploring ability to work with milliseconds, this is all i need now.

**Comment by serzhiio** [comment]
```
error[E0277]: the trait bound `std::ops::Range<chrono::datetime::DateTime<chrono::offset::utc::Utc>>: plotters::coord::ranged::Ranged` is not satisfied
   --> src\scenes\instances\components\chart\mod.rs:173:14
    |
173 |             .build_ranged(from..to, min..max).unwrap();
    |              ^^^^^^^^^^^^ the trait `plotters::coord::ranged::Ranged` is not implemented for `std::ops::Range<chrono::datetime::DateTime<chrono::offset::utc::Utc>>`
```

**Comment by 38** [comment]
No, I mean it support :`(a..b).monthly()` , `(a..b).yearly()`

But now it supports datetime completely. 

Finally get this dome ;)

**Comment by serzhiio** [comment]
Hmm.. it looks like working, but there are no labels at least on 3 minutes timespan?

**Comment by 38** [comment]
![image](https://user-images.githubusercontent.com/3023614/65921054-50b6b580-e39e-11e9-88f0-c2dc538b64e3.png)

You mean this, it works on my side. Would you like to send a minimal code reproduce what you have seen?

**Comment by serzhiio** [comment]
Its working as supposed after latest bugfix.
Is it possible to format label to show only minutes+sec like ":30:15"?

**Comment by serzhiio** [comment]
Ive managed this via `.x_lable_formatter()`.
