### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by serzhiio** [38/plotters#37]
I'm having error on this:
```
        price_chart
            .draw_series(PointSeries::new(
                (0..self.timecache.len()).map(|x| (x, self.timecache[x].2)),
                1,
                &RED,
            )).unwrap();
```
What coudl it be?
```
error[E0282]: type annotations needed
   --> src\scenes\instances\components\chart\mod.rs:108:14
    |
108 |             .draw_series(PointSeries::new(
    |              ^^^^^^^^^^^ cannot infer type for `E`
```

**Comment by 38** [comment]
Nop, `E` stands for Element. Since the point series is going to draw some pointing element on to the chart, but compiler doesn't know what types of element it should use.

Here's one of the example. 

```rust
cc.draw_series(PointSeries::<_, _, Circle<_>>::new(
        (0..6).map(|x| ((x - 3) as f32 / 1.0, ((x - 3) as f32 / 1.0).sin())),
        5,
        &RED.filled(),
    ))?;
```

I need to polish this part a little bit, alternatively, all series is actually an iterator of elements, so a simple map also works. 

```rust
cc.draw_series(
      data_iter.map(|(x,y)| Circle::new((x,y), 5 ,&RED)
)?;
```
And I found this is always easier and the point series makes everything confused. 
I am considering removing the point series for a long time.  Sorry for the confusing API.

**Comment by serzhiio** [comment]
thx
