### ISSUE TITLE
Support linspace and interval wrapper for datetime and float

### ISSUE THREAD

**Issue by serzhiio** [38/plotters#42]
Noticed that i cant draw Histogram with timeseries.
```
error[E0277]: the trait bound `plotters::coord::datetime::RangedDateTime<chrono::offset::utc::Utc>: plotters::coord::ranged::DescreteRanged` is not satisfied
   --> src\common\chart\mod.rs:189:24
    |
189 |         let buy_vols = Histogram::vertical(&vols_chart)
    |                        ^^^^^^^^^^^^^^^^^^^ the trait `plotters::coord::ranged::DescreteRanged` is not implemented for `plotters::coord::datetime::RangedDateTime<chrono::offset::utc::Utc>`
```

**Comment by 38** [comment]
This is because we currently don't have the time-slice type. Because it's not well-defined for a histogram on `DateTime` type, since we don't know the bucket size. (For example, one bar per 5 minutes, etc...)

The type slice coordinate should be added. But before that happens, you actually can draw a histogram without using the `Histogram` help. Since all the series types are just defined for convenience.

As you know the series is just a iterator of element, Thus for your case, you can actually have things like that:

```rust
       let histogram_values:Vec<(DateTime, f32)>;
       chart.draw_series( histogram_values.iter().map(|(time, value)| Rectangle::new((time, value), (time + Duration::minutes(5), value), RED.filled())?
``` 

This should just work. But you are right, the time slice should be supported. 

In addition, `Date` is automatically sliced, because it has minimal resulution which is 1 day.

For the same reason, the float number can't use the `Histogram` type, but integer can.
