### ISSUE TITLE
Change axis range preserving data

### ISSUE THREAD

**Issue by prettynatty** [38/plotters#90]
I am using incremental rendering to draw huge line series in realtime. At some point I need to increase axis range and continue drawing, previously rendered series should be rerendered.
What is authentic approach with plotters? Is there API to change range of existing ChartContext (or ChartState)?
If yes, will plotters re-render previously rendered series?
If no, I need to remember all series data, rebuild chart and render history, right?

**Comment by 38** [comment]
Hi there, unfortunately the currently API doesn't support changing range without explicit redraw the entire panel - This is due to the abstraction of series, plotters doesn't keep any series data internally (But you may implement a series wrapper does this). But I believe there's no performance difference, since we can't really do pixel-level incremental rendering.

Actually, the incremental rendering is originally designed for rendering multiple panel figures. It means we can only update one panel without redrawing other panel, but it doesn't preserve anything inside this panel - thus you need to redraw the panel anyway. But you don't need to redraw the entire figure, that's the point of this. Also, it helps improve performance by not redrawing the axis and labels each time - Sometimes this is the most expensive component to draw. 

Not sure if this helps, please let me know if you have any thoughts or suggestions.

Cheers!

**Comment by prettynatty** [comment]
Thanks, now I'm just recreating ChartContext when series exceed base range.
Also I've found out that performance degrades because my series is so dense that lots of points which are at the same pixel. I implemented a filter to reduce series density based on `dim_in_pixel`, works perfectly now. Thank you for this awesome crate!
