### ISSUE TITLE
[Feature Request] Amethyst backend

### ISSUE THREAD

**Issue by TatriX** [38/plotters#92]
### What is the feature ?
Optional [Amethyst](amethyst.rs/) integration.

### Why this feature is useful and how people would use the feature ?
Plotters already have `piston` integration, but it as far as I know, `piston` is not being actively developed, in contrast with `amethyst`.

### Additional Information
I can work on the feature, as long as you can give me some guidance ;)

**Comment by 38** [comment]
Of course, you are more than welcome to contribute :) Thanks in advance!

**Comment by 38** [comment]
Hi @TatriX , just reminds me mention this under the issue. 

I am planning separate cairo, piston and maybe amethyst backend to separate crates. Since it's quite often people directly depends on  the crate and plotters. To avoid version conflict we have to make those dependency always updated. 

So I think it's better to separate those implementation to independent crates thus we can frequently publish new version without touching the core project.

Any thoughts? See #96 for details.

**Comment by 0b01** [comment]
In my experience it's strictly better to render into a shared framebuffer which is then read by amethyst to draw as texture.
