### ISSUE TITLE
[Bug] ErrorBar element discard stroke width unexpectedly

### ISSUE THREAD

**Issue by jacobmischka** [38/plotters#93]
#40 claims that circle is the last remaining element that doesn't support stroke width, but it doesn't seem like error bar does either. It uses the style's color when drawing the lines, but disregards the stroke width causing the bar to always have a stroke width of 1.

**Comment by 38** [comment]
Oh, good catch, this is actually a bug rather than missing feature. Thanks for reporting this :)

In general, it should be supported as long as you are passing a `ShapeStyle` has customized width, but in this case, it just drop the width information. 

One thing to justify: it's true that circle is the only thing missing for the default CPU rasterizer to have width. (For the low level drawing API) But elements are high-level drawing APIs. 

Thanks so much for reporting this and I am working on a fix:)

**Comment by 38** [comment]
Believe this is fixed in master, please let me know if something is still wrong.
